# Generated by Django 5.2.7 on 2025-10-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Paciente', models.CharField(max_length=120, verbose_name='Nombre del paciente')),
                ('Descripcion_Comentario', models.TextField(max_length=1000, verbose_name='Descripcion del servicio brindado y atencion')),
                ('Calificacion', models.IntegerField(verbose_name='¡Califica nuestro servicio de 1 a 5 Estrellas!')),
                ('Foto_Paciente', models.ImageField(upload_to='Comentarios')),
                ('Fecha_Comentario', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Integrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Integrante', models.CharField(max_length=100, verbose_name='Nombre de Integrante')),
                ('Descripcion', models.TextField(max_length=800, verbose_name='Descripcion del integrante')),
                ('FotoIntegrante', models.ImageField(upload_to='Integrantes')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Servicio', models.CharField(max_length=120, verbose_name='Servicio')),
                ('Descripcion_Servicio', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('Foto_Servicio', models.ImageField(upload_to='Servicios')),
            ],
        ),
    ]
