# Generated by Django 5.2.7 on 2025-11-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SANUApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='Foto_Paciente',
            field=models.ImageField(upload_to=''),
        ),
    ]
